name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: msbuild /p:Configuration=Release /p:Platform=x64 ./project/Development.sln